#!/bin/bash

cd "$(dirname "$0")"
export LD_LIBRARY_PATH=usr/lib

# Handles desktop integration:
# 1. Copies app icons to ~/.local/share/icons
# 2. Ensures icon theme index exists
# 3. Creates a .desktop file pointing to this AppImage
# 4. Skips if a system-wide installation (/usr/share/applications) is detected
install_integration() {
    if [[ -z "$APPIMAGE" ]]; then
        return
    fi

    REAL_HOME=$(getent passwd "$USER" | cut -d: -f6)
    
    if [ -z "$REAL_HOME" ]; then
        REAL_HOME="$HOME"
    fi

    APP_NAME="fogged"
    TARGET_DESKTOP="$REAL_HOME/.local/share/applications/fogged.desktop"
    LOCAL_HICOLOR="$REAL_HOME/.local/share/icons/hicolor"
    
    if [ ! -f "$LOCAL_HICOLOR/index.theme" ]; then
        mkdir -p "$LOCAL_HICOLOR"
        if [ -f "/usr/share/icons/hicolor/index.theme" ]; then
            cp "/usr/share/icons/hicolor/index.theme" "$LOCAL_HICOLOR/"
        else
            echo -e "[Icon Theme]\nName=Hicolor\nDirectories=128x128/apps,256x256/apps" > "$LOCAL_HICOLOR/index.theme"
        fi
    fi

    if [[ -f "./fogged.png" ]]; then

        mkdir -p "$LOCAL_HICOLOR/128x128/apps"
        cp "./fogged.png" "$LOCAL_HICOLOR/128x128/apps/fogged.png"
        
        mkdir -p "$LOCAL_HICOLOR/256x256/apps"
        cp "./fogged.png" "$LOCAL_HICOLOR/256x256/apps/fogged.png"
        
        gtk-update-icon-cache -f -t "$LOCAL_HICOLOR" 2>/dev/null || true
    fi

    if [ -f "/usr/share/applications/fogged.desktop" ]; then
        return
    fi

    mkdir -p "$(dirname "$TARGET_DESKTOP")"

    cat > "$TARGET_DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Fogged
Exec="$APPIMAGE"
Icon=fogged
Terminal=false
StartupWMClass=app.fogged.com
EOF

    chmod +x "$TARGET_DESKTOP"
    update-desktop-database "$REAL_HOME/.local/share/applications" 2>/dev/null || true
}

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} ...
start Fogged or FoggedCli, when no parameter is given, Fogged is executed.
    -v              show version
EOF
}
show_version() {
    printf "Fogged version "
    jq .version <./data/flutter_assets/version.json
}
# Initialize variables:
service=0 #declare -i service
OPTIND=1

# Resetting OPTIND is necessary if getopts was used previously in the script.
# It is a good idea to make OPTIND local if you process options in a function.

# if no arg is provided, execute fogged app
if [[ $# == 0 ]];then 
    install_integration
    exec ./fogged
else

# processing arguments

    case $1 in
        FoggedCli)  
            exec ./FoggedCli ${@:3}
            exit 0
            ;;
        h)
            show_help
            exit 0
            ;;
        v)  show_version
            exit 0
            ;;
        *)
            show_help >&2
            exit 1
            ;;
    esac



fi
